BEGIN;

-- qbo_archive schema permissions
GRANT USAGE ON SCHEMA qbo_archive TO ih35_app;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA qbo_archive TO ih35_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA qbo_archive TO ih35_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA qbo_archive
  GRANT SELECT, INSERT, UPDATE ON TABLES TO ih35_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA qbo_archive
  GRANT USAGE, SELECT ON SEQUENCES TO ih35_app;

-- integrations schema permissions
GRANT USAGE ON SCHEMA integrations TO ih35_app;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA integrations TO ih35_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA integrations TO ih35_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA integrations
  GRANT SELECT, INSERT, UPDATE ON TABLES TO ih35_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA integrations
  GRANT USAGE, SELECT ON SEQUENCES TO ih35_app;

COMMIT;

