BEGIN;

-- Schema-level grants
GRANT USAGE ON SCHEMA integrations TO ih35_app;
GRANT USAGE ON SCHEMA qbo_archive TO ih35_app;
GRANT USAGE ON SCHEMA dispatch TO ih35_app;
GRANT USAGE ON SCHEMA catalogs TO ih35_app;
GRANT USAGE ON SCHEMA docs TO ih35_app;
GRANT USAGE ON SCHEMA mdata TO ih35_app;

-- Table grants for new schemas
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA integrations TO ih35_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA qbo_archive TO ih35_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA dispatch TO ih35_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA catalogs TO ih35_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA docs TO ih35_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA mdata TO ih35_app;

-- Specific grants for new tables in existing schemas
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE dispatch.load_id_reservations TO ih35_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE catalogs.company_violation_types TO ih35_app;

-- Sequences (for serial/identity columns)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA integrations TO ih35_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA qbo_archive TO ih35_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA dispatch TO ih35_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA catalogs TO ih35_app;

-- Default privileges so future objects do not regress
ALTER DEFAULT PRIVILEGES IN SCHEMA integrations
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ih35_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA integrations
  GRANT USAGE, SELECT ON SEQUENCES TO ih35_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA qbo_archive
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ih35_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA qbo_archive
  GRANT USAGE, SELECT ON SEQUENCES TO ih35_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA dispatch
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ih35_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA dispatch
  GRANT USAGE, SELECT ON SEQUENCES TO ih35_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA catalogs
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ih35_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalogs
  GRANT USAGE, SELECT ON SEQUENCES TO ih35_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA docs
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ih35_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA docs
  GRANT USAGE, SELECT ON SEQUENCES TO ih35_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA mdata
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ih35_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA mdata
  GRANT USAGE, SELECT ON SEQUENCES TO ih35_app;

COMMIT;
