-- W2A-PROFITABILITY-ENGINE: schema grants for ih35_app runtime role
CREATE SCHEMA IF NOT EXISTS analytics;
GRANT USAGE ON SCHEMA analytics TO ih35_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA analytics TO ih35_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA analytics TO ih35_app;
