-- 202615301000 · CC-3 · ROUND 340 step 1 — preserve.unit_stop_events keyed on the FULL observation grain.
-- The ledger was keyed (company_code, unit_number, started_at). A stop still in progress when it was preserved grows
-- afterwards — same start, later end — and the ledger had no slot for the later extent: re-preserving it either failed
-- or was swallowed by ON CONFLICT DO NOTHING (16 rows on prod, ROUND 340). Each extent is an observation of its own.
--   * id uuid — a surrogate generated by the ledger itself (not an app UUID; it does not die with a purge)
--   * PRIMARY KEY (id); UNIQUE (company_code, unit_number, started_at, ended_at) NULLS NOT DISTINCT
-- Nothing is deleted or updated: ADD COLUMN fills id for existing rows in the table rewrite (no row trigger fires).
-- Idempotent.
ALTER TABLE preserve.unit_stop_events ADD COLUMN IF NOT EXISTS id uuid NOT NULL DEFAULT gen_random_uuid();

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_constraint
              WHERE conrelid = 'preserve.unit_stop_events'::regclass AND contype = 'p'
                AND pg_get_constraintdef(oid) <> 'PRIMARY KEY (id)') THEN
    ALTER TABLE preserve.unit_stop_events DROP CONSTRAINT unit_stop_events_pkey;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'preserve.unit_stop_events'::regclass AND contype = 'p') THEN
    ALTER TABLE preserve.unit_stop_events ADD CONSTRAINT unit_stop_events_pkey PRIMARY KEY (id);
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_preserve_unit_stop_events_observation
  ON preserve.unit_stop_events (company_code, unit_number, started_at, ended_at) NULLS NOT DISTINCT;
