-- W2B-ALERT-RULES-PROFILES: schema grants for ih35_app runtime role
CREATE SCHEMA IF NOT EXISTS alerts;
GRANT USAGE ON SCHEMA alerts TO ih35_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA alerts TO ih35_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA alerts TO ih35_app;
