-- W3A-GEOFENCE-ENGINE: schema grants for ih35_app runtime role
CREATE SCHEMA IF NOT EXISTS geofence;
GRANT USAGE ON SCHEMA geofence TO ih35_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA geofence TO ih35_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA geofence TO ih35_app;
