-- HOLD-DEDUCTION-MODAL-WRONG-PATCH-TARGET-ID
--
-- ROOT CAUSE: driver_finance.settlement_lines (line_type='deduction') rows are generated by
-- applyPendingDeductionsToSettlementWithNetFloor (settlement-deduction-cap.service.ts) FROM a
-- driver_finance.driver_settlement_deductions row, but the INSERT never populated the table's own
-- generic linkage pair (source_table/source_reference_id, added by 202607430000 specifically for
-- "Phase-2 repoint populates these" polymorphic source-tracing). HoldDeductionModal.tsx therefore
-- sends the settlement_line's OWN id to PATCH /api/v1/driver-finance/deduction-schedules/:id/hold,
-- which updates driver_finance.deduction_schedule -- an entirely unrelated table (cash-advance/
-- liability recurring repayment schedules, never wired into the settlement engine: verified live,
-- zero backend references outside cash-advances/liabilities/legal). The settlement-line UUID can
-- never match a deduction_schedule.id (disjoint ID spaces from disjoint INSERT statements), so the
-- Hold action was fully broken by construction, not a runtime edge case.
--
-- FIX (this migration, additive/idempotent):
--   driver_settlement_deductions gets the same is_held/hold_until_period/hold_reason/
--   held_by_user_id shape deduction_schedule already carries, so the real hold PATCH endpoint
--   (added in the same PR, on driver_finance.driver_settlement_deductions -- the actual money
--   ledger, per settlement-posting.service.ts / settlement-deduction-cap.service.ts / the GL
--   poster's live usage) has somewhere to write. status stays the lifecycle column
--   (pending/partial/applied/deferred); these four are hold-specific and independent of it.
--   No settlement_lines column change is needed: source_table/source_reference_id already exist
--   and are populated by the same PR's backend change, not a new migration.
BEGIN;

ALTER TABLE driver_finance.driver_settlement_deductions
  ADD COLUMN IF NOT EXISTS is_held boolean NOT NULL DEFAULT false;
ALTER TABLE driver_finance.driver_settlement_deductions
  ADD COLUMN IF NOT EXISTS hold_until_period date NULL;
ALTER TABLE driver_finance.driver_settlement_deductions
  ADD COLUMN IF NOT EXISTS hold_reason text NULL;
ALTER TABLE driver_finance.driver_settlement_deductions
  ADD COLUMN IF NOT EXISTS held_by_user_id uuid NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'driver_settlement_deductions_held_by_user_id_fkey'
  ) THEN
    ALTER TABLE driver_finance.driver_settlement_deductions
      ADD CONSTRAINT driver_settlement_deductions_held_by_user_id_fkey
      FOREIGN KEY (held_by_user_id) REFERENCES identity.users(id);
  END IF;
END $$;

COMMIT;
