-- W1B-TASKS-MODULE: schema grants for ih35_app runtime role
GRANT USAGE ON SCHEMA tasks TO ih35_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA tasks TO ih35_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA tasks TO ih35_app;
