#!/usr/bin/env tsx
// E13-B CHART OF ACCOUNTS HYGIENE -- D2, D4, D5 (owner spec,
// ~/Downloads/09-22-2026-CC-3-E13B-CHART-HYGIENE-MEASURED.md, D4's owner-approval hold lifted
// Round 83 R2: "my earlier 'no autogenerated numbers' hold is DEAD"). D1 (5450 master) landed in
// migration 202614270000; D3 (duplicate drivers) is reported separately (docs/bus/OUTBOX-CC-3.md)
// and explicitly waits for the purge per the owner's own MERGE AFTER THE PURGE ruling -- not
// touched here.
//
// D5 -- strip "(hired unknown)" from every account name it appears in (spec said 30; measured
// live today at 42 -- the spec is stale, this script uses the live count, never the stale one).
// Applies to every row regardless of active/deactivated state -- text hygiene, not a status
// change, and the spec's own words are "all text in the app must be formatted correctly."
//
// D2 -- deactivate the 4 named test/demo accounts (2100-00-039, DRIVERCASHAD896665-045,
// 2100-00-037, DRIVERCASHAD896665-043), mirroring the real POST /:id/deactivate route's own
// UPDATE (deactivated_at = now()); void-not-delete.
//
// D4 -- rename+renumber the 6 autogenerated codes into the real numeric scheme (placed by
// account_type/subtype against the existing live chart, no collision, verified live before
// writing):
//   DRIVERCASHAD896665    -> 1245  Driver Cash Advances Receivable   (Asset, sibling of 1250
//                                  Driver Fuel-Overage Receivable)
//   DRIVERRECOVE488409    -> 7210  Driver Damage Recovery Income     (Income, sibling of 7200)
//   DRIVERTRIPLU056412    -> 5310  Lumper Expense                    (CostOfGoodsSold, sibling
//                                  of 5300 Tolls & Scales; referenced live by 2 of the 137 newly
//                                  seeded catalog items via account_id UUID, unaffected by a
//                                  number/name-only rename)
//   QBO-228-USMCA         -> 5800  Leased Trucks from IH35 TRUCKING  (CostOfGoodsSold). The "228"
//                                  QBO identifier was baked into account_number instead of the
//                                  dedicated qbo_account_id column (confirmed NULL live) --
//                                  moved there properly, not discarded.
//   TMS-INC-DRIVER-ABANDON-> 7220  Income-Driver Abandonment         (Income, sibling of 7200).
//                                  USMCA row only -- TRANSP/TRK carry the identical autogenerated
//                                  number too but are out of this session's USMCA-only scope,
//                                  same boundary already used for GL-5010's TRANSP mapping.
//   OFFICEEXPENS815299    -> RETIRED (deactivated). Duplicates 6210 "Office & Administrative
//                                  Expense" -- per spec "one of the two goes"; 6210 is the real
//                                  numbered account, OFFICEEXPENS815299 is the import artifact.
//                                  Existing postings, if any, are NOT repointed (transaction-row
//                                  work, forbidden pre-purge under Round 85/86 law) -- the
//                                  account is retired void-not-delete, not merged.
//
// No backend HTTP server reachable from this environment -- every write mirrors the REAL
// accounts.routes.ts PATCH (account_number/account_name/qbo_account_id mutable) or
// POST /:id/deactivate (deactivated_at = now()) exactly.
import path from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";

const USMCA_COMPANY_ID = "5c854333-6ea5-4faa-af31-67cb272fef80";
const OWNER_USER_ID = "e4117991-d2c0-406d-8cda-74e98d95bccd";

const D2_TEST_ACCOUNT_NUMBERS = ["2100-00-039", "DRIVERCASHAD896665-045", "2100-00-037", "DRIVERCASHAD896665-043"];

const D4_RENUMBER: { from: string; toNumber: string; toName: string; qboAccountId?: string }[] = [
  { from: "DRIVERCASHAD896665", toNumber: "1245", toName: "Driver Cash Advances Receivable" },
  { from: "DRIVERRECOVE488409", toNumber: "7210", toName: "Driver Damage Recovery Income" },
  { from: "DRIVERTRIPLU056412", toNumber: "5310", toName: "Lumper Expense" },
  { from: "QBO-228-USMCA", toNumber: "5800", toName: "Leased Trucks from IH35 TRUCKING", qboAccountId: "228" },
  { from: "TMS-INC-DRIVER-ABANDON", toNumber: "7220", toName: "Income-Driver Abandonment" },
];
const D4_RETIRE_DUPLICATE = { number: "OFFICEEXPENS815299", duplicatesOf: "6210" };

async function main() {
  const executeFlag = process.argv.includes("--execute");
  const url = process.env.DATABASE_URL ?? "";
  if (executeFlag && !process.env.ROUND271_ALLOW_HOST) throw new Error("ABORT: --execute requires ROUND271_ALLOW_HOST.");
  if (executeFlag && !url.includes(process.env.ROUND271_ALLOW_HOST!)) throw new Error("ABORT: DATABASE_URL mismatch.");
  if (/-pooler\./.test(url)) throw new Error("REFUSING pooler endpoint.");

  const pool = new pg.Pool({ connectionString: url, max: 1, ssl: { rejectUnauthorized: false } });
  const client = await pool.connect();
  await client.query("RESET ROLE");
  await client.query(`SELECT set_config('app.bypass_rls', 'lucia', true)`);
  await client.query(`SELECT set_config('app.operating_company_id', $1::text, true)`, [USMCA_COMPANY_ID]);

  // ---- measurement ----
  const hiredUnknown = await client.query<{ id: string; account_number: string; account_name: string }>(
    `SELECT id::text, account_number, account_name FROM catalogs.accounts WHERE operating_company_id = $1::uuid AND account_name ILIKE '%hired unknown%' ORDER BY account_number`,
    [USMCA_COMPANY_ID]
  );
  console.log(`D5: ${hiredUnknown.rowCount} account(s) carry "(hired unknown)" (spec said 30, stale -- using live count).`);

  const d2Rows = await client.query<{ id: string; account_number: string; account_name: string; deactivated_at: string | null }>(
    `SELECT id::text, account_number, account_name, deactivated_at FROM catalogs.accounts WHERE operating_company_id = $1::uuid AND account_number = ANY($2::text[]) ORDER BY account_number`,
    [USMCA_COMPANY_ID, D2_TEST_ACCOUNT_NUMBERS]
  );
  console.log(`D2: ${d2Rows.rowCount}/${D2_TEST_ACCOUNT_NUMBERS.length} named test accounts found live:`);
  for (const r of d2Rows.rows) console.log(`  ${r.account_number}  "${r.account_name}"  deactivated_at=${r.deactivated_at}`);

  const d4Rows = await client.query<{ id: string; account_number: string; account_name: string }>(
    `SELECT id::text, account_number, account_name FROM catalogs.accounts WHERE operating_company_id = $1::uuid AND account_number = ANY($2::text[])`,
    [USMCA_COMPANY_ID, D4_RENUMBER.map((r) => r.from)]
  );
  console.log(`D4: ${d4Rows.rowCount}/${D4_RENUMBER.length} autogenerated codes found live.`);
  const collide = await client.query<{ account_number: string }>(
    `SELECT account_number FROM catalogs.accounts WHERE operating_company_id = $1::uuid AND account_number = ANY($2::text[])`,
    [USMCA_COMPANY_ID, D4_RENUMBER.map((r) => r.toNumber)]
  );
  if (collide.rowCount) throw new Error(`ABORT: target number(s) already in use: ${collide.rows.map((r) => r.account_number).join(", ")}`);
  console.log("D4: all 5 target numbers confirmed free live.");

  const officeDupe = await client.query<{ id: string; account_number: string; account_name: string }>(
    `SELECT id::text, account_number, account_name FROM catalogs.accounts WHERE operating_company_id = $1::uuid AND account_number = $2`,
    [USMCA_COMPANY_ID, D4_RETIRE_DUPLICATE.number]
  );
  console.log(`D4 duplicate: ${D4_RETIRE_DUPLICATE.number} found = ${officeDupe.rowCount > 0}, will retire (duplicates ${D4_RETIRE_DUPLICATE.duplicatesOf}).`);

  if (!executeFlag) {
    client.release();
    await pool.end();
    console.log("\nDRY RUN -- no writes made.");
    return;
  }

  // ---- D5: strip "(hired unknown)" ----
  const d5Result = await client.query(
    `
      UPDATE catalogs.accounts
      SET account_name = trim(regexp_replace(account_name, '\\s*\\(hired unknown\\)\\s*', '', 'gi')),
          updated_by_user_id = $2::uuid
      WHERE operating_company_id = $1::uuid
        AND account_name ILIKE '%hired unknown%'
    `,
    [USMCA_COMPANY_ID, OWNER_USER_ID]
  );
  console.log(`D5: stripped "(hired unknown)" from ${d5Result.rowCount} account name(s).`);

  // ---- D2: deactivate the 4 test accounts ----
  const d2Result = await client.query(
    `
      UPDATE catalogs.accounts
      SET deactivated_at = now(), updated_by_user_id = $2::uuid
      WHERE operating_company_id = $1::uuid
        AND account_number = ANY($3::text[])
        AND deactivated_at IS NULL
      RETURNING account_number
    `,
    [USMCA_COMPANY_ID, OWNER_USER_ID, D2_TEST_ACCOUNT_NUMBERS]
  );
  console.log(`D2: deactivated ${d2Result.rowCount} test account(s): ${d2Result.rows.map((r: any) => r.account_number).join(", ")}`);

  // ---- D4: renumber the 5 autogenerated codes ----
  for (const r of D4_RENUMBER) {
    const upd = await client.query(
      `
        UPDATE catalogs.accounts
        SET account_number = $3, account_name = $4,
            qbo_account_id = COALESCE($5, qbo_account_id),
            updated_by_user_id = $2::uuid
        WHERE operating_company_id = $1::uuid AND account_number = $6
        RETURNING id::text
      `,
      [USMCA_COMPANY_ID, OWNER_USER_ID, r.toNumber, r.toName, r.qboAccountId ?? null, r.from]
    );
    console.log(`D4: ${r.from} -> ${r.toNumber} "${r.toName}" (${upd.rowCount} row)`);
  }

  // ---- D4: retire the OFFICEEXPENS815299 / 6210 duplicate ----
  const officeResult = await client.query(
    `
      UPDATE catalogs.accounts
      SET deactivated_at = now(), updated_by_user_id = $2::uuid,
          notes = COALESCE(notes || ' ', '') || 'Retired -- duplicates 6210 Office & Administrative Expense (E13-B D4).'
      WHERE operating_company_id = $1::uuid AND account_number = $3 AND deactivated_at IS NULL
      RETURNING account_number
    `,
    [USMCA_COMPANY_ID, OWNER_USER_ID, D4_RETIRE_DUPLICATE.number]
  );
  console.log(`D4: retired ${officeResult.rowCount} duplicate account(s): ${officeResult.rows.map((r: any) => r.account_number).join(", ")}`);

  client.release();
  await pool.end();
  console.log("\nDone.");
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) await main();
