-- ITEM CATALOG SEED — 137 items, 20 categories. Generated by build_catalog_seed_sql.py
-- Owner rulings Round 83 (items carry quantity), 87 (accessorials + company vehicle use
-- fee) and 88 (six driver deductions mirroring the 49xx short-pay reasons).
-- PREREQUISITES: catalogs.item_categories exists; accounts 6250/6255/6260/5450 exist.
-- IDEMPOTENT: safe to re-run. Inserts nothing that is already there.

BEGIN;
SET LOCAL app.bypass_rls = 'lucia';

-- FAIL LOUDLY IF A PREREQUISITE IS MISSING. A silent NULL account is how bad data starts.
DO $$
BEGIN
  IF to_regclass('catalogs.item_categories') IS NULL THEN
    RAISE EXCEPTION 'catalogs.item_categories does not exist — the item/line schema must land first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '4000'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 4000 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '4100'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 4100 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '4200'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 4200 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '4210'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 4210 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '4220'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 4220 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '4230'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 4230 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '4240'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 4240 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '4910'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 4910 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '4930'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 4930 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '5000'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 5000 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '5100'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 5100 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '5300'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 5300 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '5400'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 5400 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '5450'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 5450 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '5500'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 5500 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '5700'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 5700 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '6100'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 6100 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '6160'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 6160 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '6255'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 6255 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '6260'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 6260 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '6300'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 6300 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '6500'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 6500 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '6600'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 6600 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '6890'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 6890 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = '7200'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account 7200 is missing — run the four-account migration first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM catalogs.accounts WHERE account_number = 'DRIVERTRIPLU056412'
                 AND operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL) THEN
    RAISE EXCEPTION 'account DRIVERTRIPLU056412 is missing — run the four-account migration first';
  END IF;
END $$;

-- 1. CATEGORIES
INSERT INTO catalogs.item_categories (id, operating_company_id, name, sort_order, is_active)
VALUES
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Sales of Service Income', 1, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Driver Salaries', 2, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Operational Licenses, Permits & Taxes', 3, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Scale Expense', 4, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Fuel Expenses', 5, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Driver Deductions', 6, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Driver Reimbursements', 7, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Repair & Maintenance-Over the Road', 8, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Software Expenses', 9, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Bank Charges', 10, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Freight Delivery Costs', 11, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Bridge & Toll Expenses', 12, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Employees-Payroll & Contractors', 13, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Building Rent & Lease Expense', 14, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Utilities Expense', 15, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Repair & Maintenance-Roadservice', 16, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Repair & Maintenance-IH 35-Internal Mechanic Shop', 17, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Repair & Maintenance-Local External Mechanic Shop', 18, true),
  (gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', 'Travel Expenses-Drivers', 19, true)
ON CONFLICT (operating_company_id, name) DO NOTHING;

-- 2. ITEMS. Category and account resolved by lookup, never by a pasted id.
WITH src (item_category, item_name, item_type, item_code, description,
          account_number, posts_to, mirrors_shortpay) AS (VALUES
  ('Sales of Service Income', 'Line Haul', 'Service', 'SALES-OF-SER-LINE-HAUL', 'Line Haul', '4000', 'revenue', ''),
  ('', 'Hours', 'Service', 'HOURS', '', '5100', 'expense', ''),
  ('Sales of Service Income', 'Warehouse-Lumper Fee', 'Service', 'SALES-OF-SER-WAREHOUSE-LUMPER-FEE', 'Warehouse-Lumper Fee', '4230', 'revenue', ''),
  ('', 'Fuel Surcharge', 'Service', 'FUEL-SURCHARGE', '', '4100', 'expense', ''),
  ('Sales of Service Income', 'Layover Charge', 'Service', 'SALES-OF-SER-LAYOVER-CHARGE', 'Layover Charge', '4220', 'revenue', ''),
  ('Sales of Service Income', 'Customer Expense-Product Disposal-Fee', 'Service', 'SALES-OF-SER-CUSTOMER-EXPENSE-PRODUCT-DISPOSAL-FEE', 'Customer Expense-Product Disposal-Fee', '4200', 'revenue', ''),
  ('Sales of Service Income', 'Sales-Transload', 'Service', 'SALES-OF-SER-SALES-TRANSLOAD', 'Sales-Transload', '4200', 'revenue', ''),
  ('Sales of Service Income', 'Extra Delivery-Pick/Drop', 'Service', 'SALES-OF-SER-EXTRA-DELIVERY-PICK-DROP', 'Extra Delivery-Pick/Drop', '4200', 'revenue', ''),
  ('Sales of Service Income', 'Sales-Detention Charge', 'Service', 'SALES-OF-SER-SALES-DETENTION-CHARGE', 'Sales-Detention Charge', '4210', 'revenue', ''),
  ('Sales of Service Income', 'Deduction-For Damaged Product', 'Service', 'SALES-OF-SER-DEDUCTION-FOR-DAMAGED-PRODUCT', 'Deduction-For Damaged Product', '4930', 'revenue', ''),
  ('Sales of Service Income', 'Customer Pmt-Fuel Advance', 'NonInventory', 'SALES-OF-SER-CUSTOMER-PMT-FUEL-ADVANCE', 'Customer Pmt-Fuel Advance', '4200', 'revenue', ''),
  ('Driver Salaries', 'Driver Pay-Extra Pick/Delivery-Drop', 'Service', 'DRIVER-SALAR-DRIVER-PAY-EXTRA-PICK-DELIVERY-DROP', '', '5100', 'expense', ''),
  ('Sales of Service Income', 'Deduction-Charge for Damages', 'Service', 'SALES-OF-SER-DEDUCTION-CHARGE-FOR-DAMAGES', '11478     Damages', '4930', 'revenue', ''),
  ('Sales of Service Income', 'Sales-Permit Fee Expense', 'Service', 'SALES-OF-SER-SALES-PERMIT-FEE-EXPENSE', 'Sales-Permit Fee Expense', '4200', 'revenue', ''),
  ('Operational Licenses, Permits & Taxes', 'Oversize Permit', 'Service', 'OPERATIONAL-OVERSIZE-PERMIT', '', '5700', 'expense', ''),
  ('Driver Salaries', 'Driver Pay-Mexico-B1 Driver-Empty Miles', 'Service', 'DRIVER-SALAR-DRIVER-PAY-MEXICO-B1-DRIVER-EMPTY-MILES', '', '5100', 'expense', ''),
  ('Driver Salaries', 'Driver Pay-Mexico-B1 Driver-Loaded Miles', 'Service', 'DRIVER-SALAR-DRIVER-PAY-MEXICO-B1-DRIVER-LOADED-MILES', '', '5100', 'expense', ''),
  ('Scale Expense', 'OTR-Scale Expense', 'Service', 'SCALE-EXPENS-OTR-SCALE-EXPENSE', '', '5300', 'expense', ''),
  ('Fuel Expenses', 'Fuel-Truck Diesel', 'NonInventory', 'FUEL-EXPENSE-FUEL-TRUCK-DIESEL', '', '5000', 'expense', ''),
  ('Fuel Expenses', 'Fuel-Reefer-Diesel', 'NonInventory', 'FUEL-EXPENSE-FUEL-REEFER-DIESEL', '', '5000', 'expense', ''),
  ('Sales of Service Income', 'Customer Expense-Reefer-Trailer-Washout', 'Service', 'SALES-OF-SER-CUSTOMER-EXPENSE-REEFER-TRAILER-WASHOUT', 'Customer Expense-Reefer-Trailer-Washout', '4200', 'revenue', ''),
  ('Fuel Expenses', 'Fuel-DEF-Diesel Exhaust Fluid', 'NonInventory', 'FUEL-EXPENSE-FUEL-DEF-DIESEL-EXHAUST-FLUID', '', '5000', 'expense', ''),
  ('Driver Deductions', 'Driver Deduction-Escrow for Claims-2026', 'NonInventory', 'DRIVER-DEDUC-DRIVER-DEDUCTION-ESCROW-FOR-CLAIMS-2026', 'Driver Deduction-Escrow for Claims-2026', '7200', 'income', ''),
  ('Driver Salaries', 'Driver Pay-Layover-Estancia', 'Service', 'DRIVER-SALAR-DRIVER-PAY-LAYOVER-ESTANCIA', '', '5100', 'expense', ''),
  ('Driver Salaries', 'Driver Pay-Bonus', 'Service', 'DRIVER-SALAR-DRIVER-PAY-BONUS', '', '5100', 'expense', ''),
  ('Driver Salaries', 'Driver Pay-Tarp-Enlonada/Desenlonada', 'Service', 'DRIVER-SALAR-DRIVER-PAY-TARP-ENLONADA-DESENLONADA', '', '5100', 'expense', ''),
  ('Driver Salaries', 'Driver Pay-Local Movement', 'Service', 'DRIVER-SALAR-DRIVER-PAY-LOCAL-MOVEMENT', '', '5100', 'expense', ''),
  ('Driver Salaries', 'Driver Pay-Oversize Load', 'Service', 'DRIVER-SALAR-DRIVER-PAY-OVERSIZE-LOAD', '', '5100', 'expense', ''),
  ('Sales of Service Income', 'Shag Fee', 'Service', 'SALES-OF-SER-SHAG-FEE', 'Shag Fee', '4200', 'revenue', ''),
  ('Driver Reimbursements', 'Driver Reimbursement-Fuel Def', 'NonInventory', 'DRIVER-REIMB-DRIVER-REIMBURSEMENT-FUEL-DEF', '', '5000', 'expense', ''),
  ('Driver Reimbursements', 'Driver Reimbursement-OTR-Maintenance, Oils, Additives', 'NonInventory', 'DRIVER-REIMB-DRIVER-REIMBURSEMENT-OTR-MAINTENANCE-OILS-ADDIT', '', '5400', 'expense', ''),
  ('Driver Reimbursements', 'Driver Reimbursement-TPE-Toll Expense', 'NonInventory', 'DRIVER-REIMB-DRIVER-REIMBURSEMENT-TPE-TOLL-EXPENSE', '', '5300', 'expense', ''),
  ('Driver Reimbursements', 'Driver Reimbursement-Scale Expense', 'NonInventory', 'DRIVER-REIMB-DRIVER-REIMBURSEMENT-SCALE-EXPENSE', '', '5300', 'expense', ''),
  ('Driver Deductions', 'Driver Deduction-Express Code Fee', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTION-EXPRESS-CODE-FEE', '', '7200', 'income', ''),
  ('Driver Deductions', 'Driver Deduction-Fines & Violations', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTION-FINES-VIOLATIONS', '', '7200', 'income', ''),
  ('Driver Deductions', 'Driver Deduction-I-94 Permit', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTION-I-94-PERMIT', '', '7200', 'income', ''),
  ('Driver Deductions', 'Driver Deduction-Wire & ACH Fee', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTION-WIRE-ACH-FEE', '', '7200', 'income', ''),
  ('Driver Deductions', 'Driver Deduction-Fine-Late Delivery Fee', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTION-FINE-LATE-DELIVERY-FEE', '', '7200', 'income', ''),
  ('Sales of Service Income', 'Deduction-Company Fine-For Late Delivery', 'Service', 'SALES-OF-SER-DEDUCTION-COMPANY-FINE-FOR-LATE-DELIVERY', 'Deduction-Company Fine-For Late Delivery', '4910', 'revenue', ''),
  ('Repair & Maintenance-Over the Road', 'OTR-Additives, Oil, Antifreeze', 'NonInventory', 'REPAIR-MAI-OTR-ADDITIVES-OIL-ANTIFREEZE', '', '6160', 'expense', ''),
  ('Software Expenses', 'Google', 'Service', 'SOFTWARE-EXP-GOOGLE', '', '6500', 'expense', ''),
  ('Software Expenses', 'All-ways Track', 'Service', 'SOFTWARE-EXP-ALL-WAYS-TRACK', '', '6500', 'expense', ''),
  ('Software Expenses', 'Anydesk', 'Service', 'SOFTWARE-EXP-ANYDESK', '', '6500', 'expense', ''),
  ('Software Expenses', 'Apple', 'Service', 'SOFTWARE-EXP-APPLE', '', '6500', 'expense', ''),
  ('Software Expenses', 'Credit Score', 'Service', 'SOFTWARE-EXP-CREDIT-SCORE', '', '6500', 'expense', ''),
  ('Software Expenses', 'Dat Solutions-360', 'Service', 'SOFTWARE-EXP-DAT-SOLUTIONS-360', '', '6500', 'expense', ''),
  ('Software Expenses', 'Intuit Quick Books', 'Service', 'SOFTWARE-EXP-INTUIT-QUICK-BOOKS', '', '6500', 'expense', ''),
  ('Software Expenses', 'Saasant Software', 'Service', 'SOFTWARE-EXP-SAASANT-SOFTWARE', '', '6500', 'expense', ''),
  ('Software Expenses', 'Samsara-GPS', 'Service', 'SOFTWARE-EXP-SAMSARA-GPS', '', '6500', 'expense', ''),
  ('Driver Salaries', 'Driver Pay-CDL-Empty Miles', 'Service', 'DRIVER-SALAR-DRIVER-PAY-CDL-EMPTY-MILES', '', '5100', 'expense', ''),
  ('Driver Salaries', 'Driver Pay-CDL-Loaded Miles', 'Service', 'DRIVER-SALAR-DRIVER-PAY-CDL-LOADED-MILES', '', '5100', 'expense', ''),
  ('Repair & Maintenance-Over the Road', 'OTR-Maintenance-Tools', 'NonInventory', 'REPAIR-MAI-OTR-MAINTENANCE-TOOLS', '', '6160', 'expense', ''),
  ('Driver Reimbursements', 'Driver Reimbursement Warehouse-Lumper Fee', 'NonInventory', 'DRIVER-REIMB-DRIVER-REIMBURSEMENT-WAREHOUSE-LUMPER-FEE', '', 'DRIVERTRIPLU056412', 'expense', ''),
  ('Driver Deductions', 'Driver-Deductions-Miscellaneous', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTIONS-MISCELLANEOUS', '', '7200', 'income', ''),
  ('Bank Charges', 'BC-Bank Ach & Wire Fees', 'Service', 'BANK-CHARGES-BC-BANK-ACH-WIRE-FEES', '', '6300', 'expense', ''),
  ('Freight Delivery Costs', 'Reefer-Trailer Washout Expense', 'Service', 'FREIGHT-DELI-REEFER-TRAILER-WASHOUT-EXPENSE', '', '5300', 'expense', ''),
  ('Bridge & Toll Expenses', 'Bridge Toll Exp-Dtops-Bridge Tolls-USA', 'Service', 'BRIDGE-TOL-BRIDGE-TOLL-EXP-DTOPS-BRIDGE-TOLLS-USA', '', '5300', 'expense', ''),
  ('Operational Licenses, Permits & Taxes', 'Kentucky-State Permits', 'NonInventory', 'OPERATIONAL-KENTUCKY-STATE-PERMITS', '', '5700', 'expense', ''),
  ('Freight Delivery Costs', 'Driver Antidoping Expense', 'NonInventory', 'FREIGHT-DELI-DRIVER-ANTIDOPING-EXPENSE', '', '5300', 'expense', ''),
  ('Operational Licenses, Permits & Taxes', 'State Permits-New Mexico', 'NonInventory', 'OPERATIONAL-STATE-PERMITS-NEW-MEXICO', '', '5700', 'expense', ''),
  ('Operational Licenses, Permits & Taxes', 'State Permits-Arkansas', 'Service', 'OPERATIONAL-STATE-PERMITS-ARKANSAS', '', '5700', 'expense', ''),
  ('Bank Charges', 'BC-ComData Express Check Fee', 'Service', 'BANK-CHARGES-BC-COMDATA-EXPRESS-CHECK-FEE', '', '6300', 'expense', ''),
  ('Bank Charges', 'BC-Monthly Bank Charge', 'Service', 'BANK-CHARGES-BC-MONTHLY-BANK-CHARGE', '', '6300', 'expense', ''),
  ('Bank Charges', 'BC-NSF Fee', 'Service', 'BANK-CHARGES-BC-NSF-FEE', '', '6300', 'expense', ''),
  ('Employees-Payroll & Contractors', 'Mecanics-Nuevo Laredo', 'Service', 'EMPLOYEES-PA-MECANICS-NUEVO-LAREDO', '', '6890', 'expense', ''),
  ('Employees-Payroll & Contractors', 'Mecanics-Laredo Texas', 'Service', 'EMPLOYEES-PA-MECANICS-LAREDO-TEXAS', '', '6890', 'expense', ''),
  ('Employees-Payroll & Contractors', 'Dispatcher Services-USA', 'Service', 'EMPLOYEES-PA-DISPATCHER-SERVICES-USA', '', '6890', 'expense', ''),
  ('Employees-Payroll & Contractors', 'Dispatcher Services-Mexico', 'Service', 'EMPLOYEES-PA-DISPATCHER-SERVICES-MEXICO', '', '6890', 'expense', ''),
  ('Employees-Payroll & Contractors', 'Safety Officer Services', 'Service', 'EMPLOYEES-PA-SAFETY-OFFICER-SERVICES', '', '6890', 'expense', ''),
  ('Employees-Payroll & Contractors', 'Mecanics-Extra Pay', 'Service', 'EMPLOYEES-PA-MECANICS-EXTRA-PAY', '', '6890', 'expense', ''),
  ('Employees-Payroll & Contractors', 'Nomina-Operador Local', 'Service', 'EMPLOYEES-PA-NOMINA-OPERADOR-LOCAL', '', '6890', 'expense', ''),
  ('Employees-Payroll & Contractors', 'Employees-Data Entry Nuevo Laredo', 'Service', 'EMPLOYEES-PA-EMPLOYEES-DATA-ENTRY-NUEVO-LAREDO', '', '6890', 'expense', ''),
  ('Building Rent & Lease Expense', 'Rent-Office-Laredo, Texas', 'Service', 'BUILDING-REN-RENT-OFFICE-LAREDO-TEXAS', '', '6255', 'expense', ''),
  ('Building Rent & Lease Expense', 'Rent-Office-Nuevo Laredo', 'Service', 'BUILDING-REN-RENT-OFFICE-NUEVO-LAREDO', '', '6255', 'expense', ''),
  ('Building Rent & Lease Expense', 'Rent-Truck Yard-Colombia, Nuevo León', 'Service', 'BUILDING-REN-RENT-TRUCK-YARD-COLOMBIA-NUEVO-LE-N', '', '6260', 'expense', ''),
  ('Utilities Expense', 'UE-Electricity', 'Service', 'UTILITIES-EX-UE-ELECTRICITY', '', '6100', 'expense', ''),
  ('Utilities Expense', 'UE-Sanitation & Waste Mgmt', 'Service', 'UTILITIES-EX-UE-SANITATION-WASTE-MGMT', '', '6100', 'expense', ''),
  ('Utilities Expense', 'UE-Sewer & Water', 'Service', 'UTILITIES-EX-UE-SEWER-WATER', '', '6100', 'expense', ''),
  ('Utilities Expense', 'UE-Telephone & Internet', 'Service', 'UTILITIES-EX-UE-TELEPHONE-INTERNET', '', '6100', 'expense', ''),
  ('Operational Licenses, Permits & Taxes', 'Permit-IRP-License Plates-Texas', 'Service', 'OPERATIONAL-PERMIT-IRP-LICENSE-PLATES-TEXAS', '', '5700', 'expense', ''),
  ('Operational Licenses, Permits & Taxes', 'Permit-License Plates-Mexico', 'Service', 'OPERATIONAL-PERMIT-LICENSE-PLATES-MEXICO', '', '5700', 'expense', ''),
  ('Operational Licenses, Permits & Taxes', 'Tax-2290-Heavy Highway Vehicle Tax', 'Service', 'OPERATIONAL-TAX-2290-HEAVY-HIGHWAY-VEHICLE-TAX', '', '5700', 'expense', ''),
  ('Operational Licenses, Permits & Taxes', 'Tax-IFTA-Motor Fuel Tax', 'Service', 'OPERATIONAL-TAX-IFTA-MOTOR-FUEL-TAX', '', '5700', 'expense', ''),
  ('Operational Licenses, Permits & Taxes', 'Tax-Unified Carrier-UCR', 'Service', 'OPERATIONAL-TAX-UNIFIED-CARRIER-UCR', '', '5700', 'expense', ''),
  ('Operational Licenses, Permits & Taxes', 'Tax-Vehicle Inspection', 'Service', 'OPERATIONAL-TAX-VEHICLE-INSPECTION', '', '5700', 'expense', ''),
  ('Operational Licenses, Permits & Taxes', 'Permits-Mexico', 'Service', 'OPERATIONAL-PERMITS-MEXICO', '', '5700', 'expense', ''),
  ('Bridge & Toll Expenses', 'Highway Toll Expense-USA', 'Service', 'BRIDGE-TOL-HIGHWAY-TOLL-EXPENSE-USA', '', '5300', 'expense', ''),
  ('Bridge & Toll Expenses', 'Highway Toll Expense-Mexico', 'Service', 'BRIDGE-TOL-HIGHWAY-TOLL-EXPENSE-MEXICO', '', '5300', 'expense', ''),
  ('Bridge & Toll Expenses', 'Bridge Toll Expense-Mexico', 'Service', 'BRIDGE-TOL-BRIDGE-TOLL-EXPENSE-MEXICO', '', '5300', 'expense', ''),
  ('Employees-Payroll & Contractors', 'Accounting & Bookkeeping Employees', 'Service', 'EMPLOYEES-PA-ACCOUNTING-BOOKKEEPING-EMPLOYEES', '', '6890', 'expense', ''),
  ('Repair & Maintenance-Roadservice', 'Road Service-Reefer Repair Expense', 'Service', 'REPAIR-MAI-ROAD-SERVICE-REEFER-REPAIR-EXPENSE', '', '5450', 'expense', ''),
  ('Repair & Maintenance-Roadservice', 'Road Service-Flatbed Repair Expense', 'Service', 'REPAIR-MAI-ROAD-SERVICE-FLATBED-REPAIR-EXPENSE', '', '5450', 'expense', ''),
  ('Repair & Maintenance-Roadservice', 'Road Service-Trailer Tire Expense', 'Service', 'REPAIR-MAI-ROAD-SERVICE-TRAILER-TIRE-EXPENSE', '', '5500', 'expense', ''),
  ('Repair & Maintenance-Roadservice', 'Road Service-Truck Repair Expense', 'Service', 'REPAIR-MAI-ROAD-SERVICE-TRUCK-REPAIR-EXPENSE', '', '5400', 'expense', ''),
  ('Repair & Maintenance-Roadservice', 'Road Service-Truck Tire Expense', 'Service', 'REPAIR-MAI-ROAD-SERVICE-TRUCK-TIRE-EXPENSE', '', '5500', 'expense', ''),
  ('Repair & Maintenance-IH 35-Internal Mechanic Shop', 'IH 35-Internal-Oil & Additive Expense (617)', 'Service', 'REPAIR-MAI-IH-35-INTERNAL-OIL-ADDITIVE-EXPENSE-617', '', '6160', 'expense', ''),
  ('Repair & Maintenance-IH 35-Internal Mechanic Shop', 'IH 35-Internal-Trailer Repair & Maintenance', 'Service', 'REPAIR-MAI-IH-35-INTERNAL-TRAILER-REPAIR-MAINTENANCE', '', '5450', 'expense', ''),
  ('Repair & Maintenance-IH 35-Internal Mechanic Shop', 'IH 35-Internal-Reefer Tire Expense', 'Service', 'REPAIR-MAI-IH-35-INTERNAL-REEFER-TIRE-EXPENSE', '', '5500', 'expense', ''),
  ('Repair & Maintenance-IH 35-Internal Mechanic Shop', 'IH 35-Internal-Truck Repair & Maintenance', 'Service', 'REPAIR-MAI-IH-35-INTERNAL-TRUCK-REPAIR-MAINTENANCE', '', '5400', 'expense', ''),
  ('Repair & Maintenance-IH 35-Internal Mechanic Shop', 'IH 35-Internal-Truck-Tire Expenses', 'Service', 'REPAIR-MAI-IH-35-INTERNAL-TRUCK-TIRE-EXPENSES', '', '5500', 'expense', ''),
  ('Repair & Maintenance-Local External Mechanic Shop', 'External Mechanic Shop-Trailer Repair', 'Service', 'REPAIR-MAI-EXTERNAL-MECHANIC-SHOP-TRAILER-REPAIR', '', '5450', 'expense', ''),
  ('Repair & Maintenance-Local External Mechanic Shop', 'External Mechanic Shop-Tractor-Truck', 'Service', 'REPAIR-MAI-EXTERNAL-MECHANIC-SHOP-TRACTOR-TRUCK', '', '5400', 'expense', ''),
  ('Driver Deductions', 'Driver Deduction-For Accident & Damages to Equipment', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTION-FOR-ACCIDENT-DAMAGES-TO-EQUIPM', '', '7200', 'income', ''),
  ('Driver Deductions', 'Driver Deduction-Meals', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTION-MEALS', '', '7200', 'income', ''),
  ('Sales of Service Income', 'Sales-International Border Crossing', 'Service', 'SALES-OF-SER-SALES-INTERNATIONAL-BORDER-CROSSING', 'Sales-International Border Crossing', '4200', 'revenue', ''),
  ('Travel Expenses-Drivers', 'Driver Meals Expense', 'Service', 'TRAVEL-EXPEN-DRIVER-MEALS-EXPENSE', '', '5100', 'expense', ''),
  ('Travel Expenses-Drivers', 'Driver-Hotel/Lodging Expense', 'Service', 'TRAVEL-EXPEN-DRIVER-HOTEL-LODGING-EXPENSE', '', '5100', 'expense', ''),
  ('Sales of Service Income', 'Sales-Escort Expense', 'Service', 'SALES-OF-SER-SALES-ESCORT-EXPENSE', 'Sales-Escort Expense', '4200', 'revenue', ''),
  ('Freight Delivery Costs', 'Escort Expense', 'Service', 'FREIGHT-DELI-ESCORT-EXPENSE', '', '5300', 'expense', ''),
  ('Bridge & Toll Expenses', 'OTR-Parking Expense', 'Service', 'BRIDGE-TOL-OTR-PARKING-EXPENSE', '', '5300', 'expense', ''),
  ('Employees-Payroll & Contractors', 'Human Resources-Employee Finder', 'Service', 'EMPLOYEES-PA-HUMAN-RESOURCES-EMPLOYEE-FINDER', '', '6890', 'expense', ''),
  ('Repair & Maintenance-IH 35-Internal Mechanic Shop', 'IH 35-Internal-Flatbed Trailer Tire Expense', 'Service', 'REPAIR-MAI-IH-35-INTERNAL-FLATBED-TRAILER-TIRE-EXPENSE', '', '5500', 'expense', ''),
  ('Operational Licenses, Permits & Taxes', 'State Permit-Oklahoma', 'Service', 'OPERATIONAL-STATE-PERMIT-OKLAHOMA', '', '5700', 'expense', ''),
  ('Driver Salaries', 'Petty Cash Advance-Caja Chica', 'Service', 'DRIVER-SALAR-PETTY-CASH-ADVANCE-CAJA-CHICA', '', '5100', 'expense', ''),
  ('Freight Delivery Costs', 'Documentos Cruces-Manifiestos, Etc', 'Service', 'FREIGHT-DELI-DOCUMENTOS-CRUCES-MANIFIESTOS-ETC', '', '5300', 'expense', ''),
  ('Driver Salaries', 'Driver Pay-Extra for Repairs-Maintenance', 'Service', 'DRIVER-SALAR-DRIVER-PAY-EXTRA-FOR-REPAIRS-MAINTENANCE', '', '5100', 'expense', ''),
  ('Driver Deductions', 'Driver Deduction-Personal Expenses-Telephone, etc', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTION-PERSONAL-EXPENSES-TELEPHONE-ET', '', '7200', 'income', ''),
  ('', 'DOWN PAYMENT INSURANCE', 'Service', 'DOWN-PAYMENT-INSURANCE', '', '6600', 'expense', ''),
  ('Bank Charges', 'BC-Relay Wire Fees', 'Service', 'BANK-CHARGES-BC-RELAY-WIRE-FEES', '', '6300', 'expense', ''),
  ('Bank Charges', 'BC-Relay Diesel Code Fee', 'Service', 'BANK-CHARGES-BC-RELAY-DIESEL-CODE-FEE', '', '6300', 'expense', ''),
  ('Software Expenses', 'Chat Gpt Software', 'Service', 'SOFTWARE-EXP-CHAT-GPT-SOFTWARE', '', '6500', 'expense', ''),
  ('Software Expenses', 'Employee Hiring Software', 'Service', 'SOFTWARE-EXP-EMPLOYEE-HIRING-SOFTWARE', '', '6500', 'expense', ''),
  ('Freight Delivery Costs', 'Warehouse Lumper Expense', 'Service', 'FREIGHT-DELI-WAREHOUSE-LUMPER-EXPENSE', '', 'DRIVERTRIPLU056412', 'expense', ''),
  ('Software Expenses', 'Alvys-Software', 'Service', 'SOFTWARE-EXP-ALVYS-SOFTWARE', '', '6500', 'expense', ''),
  ('', 'TONU', 'NonInventory', 'TONU', 'Truck order Not Used', '4240', 'expense', ''),
  ('Sales of Service Income', 'Sales-Local Movement', 'Service', 'SALES-OF-SER-SALES-LOCAL-MOVEMENT', 'Sales-Local Movement', '4200', 'revenue', ''),
  ('Sales of Service Income', 'Sales-Tracking/MacroPoint Compliance', 'Service', 'SALES-OF-SER-SALES-TRACKING-MACROPOINT-COMPLIANCE', '', '4200', 'revenue', ''),
  ('Sales of Service Income', 'Sales-On-Time Pickup Appointment', 'Service', 'SALES-OF-SER-SALES-ON-TIME-PICKUP-APPOINTMENT', '', '4200', 'revenue', ''),
  ('Sales of Service Income', 'Sales-On-Time Delivery Appointment', 'Service', 'SALES-OF-SER-SALES-ON-TIME-DELIVERY-APPOINTMENT', '', '4200', 'revenue', ''),
  ('Sales of Service Income', 'Sales-Tarp Charge', 'Service', 'SALES-OF-SER-SALES-TARP-CHARGE', '', '4200', 'revenue', ''),
  ('Driver Deductions', 'Driver Deduction-Company Vehicle Use Fee', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTION-COMPANY-VEHICLE-USE-FEE', '', '7200', 'income', ''),
  ('Driver Deductions', 'Driver Deduction-Missing or Late Paperwork/POD', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTION-MISSING-OR-LATE-PAPERWORK-POD', '', '7200', 'income', '4920'),
  ('Driver Deductions', 'Driver Deduction-Lumper Not Paid or Receipt Missing', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTION-LUMPER-NOT-PAID-OR-RECEIPT-MIS', '', '7200', 'income', '4920'),
  ('Driver Deductions', 'Driver Deduction-Cargo Damage OS&D', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTION-CARGO-DAMAGE-OS-D', '', '7200', 'income', '4930'),
  ('Driver Deductions', 'Driver Deduction-Detention Denied - Driver Delay', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTION-DETENTION-DENIED-DRIVER-DELAY', '', '7200', 'income', '4950'),
  ('Driver Deductions', 'Driver Deduction-Missed Appointment', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTION-MISSED-APPOINTMENT', '', '7200', 'income', '4910'),
  ('Driver Deductions', 'Driver Deduction-Load Not Tarped or Secured', 'Service', 'DRIVER-DEDUC-DRIVER-DEDUCTION-LOAD-NOT-TARPED-OR-SECURED', '', '7200', 'income', '4980')
)
INSERT INTO catalogs.items
  (id, operating_company_id, item_name, item_code, item_type, description,
   category_id, default_income_account_id, default_expense_account_id, notes)
SELECT gen_random_uuid(), '5c854333-6ea5-4faa-af31-67cb272fef80', s.item_name, s.item_code, s.item_type,
       NULLIF(s.description, ''),
       c.id,
       CASE WHEN s.posts_to IN ('revenue','income') THEN a.id END,
       CASE WHEN s.posts_to NOT IN ('revenue','income') THEN a.id END,
       NULLIF(s.mirrors_shortpay, '')
FROM src s
LEFT JOIN catalogs.item_categories c
       ON c.name = s.item_category AND c.operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80'
JOIN catalogs.accounts a
       ON a.account_number = s.account_number
      AND a.operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND a.deactivated_at IS NULL
ON CONFLICT (operating_company_id, item_code) DO NOTHING;

-- 3. RETIRE THE TEST ITEMS. Void-not-delete: they keep their history.
UPDATE catalogs.items SET deactivated_at = now()
 WHERE operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL
   AND (item_code IN ('CC2-BATTERY-20260807','P42-VFK-ITEM-0811',
                      'TESTCC3-MAINT-20260825','ZZ-GATEB-A','ZZ-GATEB-B')
    OR item_name ~* '^(TEST|ZZ-SAMPLE|CC2-|P42 )');

-- 4. PROOF, in the same transaction.
SELECT 'categories' AS what, count(*) AS n FROM catalogs.item_categories
 WHERE operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80'
UNION ALL SELECT 'items active', count(*) FROM catalogs.items
 WHERE operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL
UNION ALL SELECT 'items with NO account', count(*) FROM catalogs.items
 WHERE operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL
   AND default_income_account_id IS NULL AND default_expense_account_id IS NULL
UNION ALL SELECT 'items with NO category', count(*) FROM catalogs.items
 WHERE operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL
   AND category_id IS NULL
UNION ALL SELECT 'test items still active', count(*) FROM catalogs.items
 WHERE operating_company_id = '5c854333-6ea5-4faa-af31-67cb272fef80' AND deactivated_at IS NULL
   AND item_name ~* '^(TEST|ZZ-SAMPLE|CC2-|P42 )';

-- EXPECT: categories 19 · items active 137 · NO account 0 · NO category 2 (Hours, TONU are uncategorised in QBO) · test 0
COMMIT;
