/**
 * E-41 — Engine status board catalog (Round 306).
 * Source: docs/engines/IH35-ENGINE-REGISTRY-2026-10-01.xlsx sheet "1 ENGINES".
 * shouldProduce = built engine expected to write rows; screens / pure-on-read stay false.
 */
export type EngineOutputProbe = {
  /** schema.table — counted with to_regclass guard */
  relation: string;
  /** timestamp column for 24h window (created_at / occurred_at / started_at / captured_at) */
  tsColumn: string;
  /** optional company scope column; null = global/company-agnostic count */
  companyColumn?: string | null;
};

export type EngineCatalogEntry = {
  id: string;
  name: string;
  module: string;
  domain: string;
  schedule: string;
  /** hours; null = no production window (screen / on-read / pending) */
  expectedWindowHours: number | null;
  shouldProduce: boolean;
  /** integrations.integration_sync_log.sync_kind values when known */
  syncKinds: string[];
  output: EngineOutputProbe | null;
  ownerSeat: string;
  kind: "engine" | "screen" | "pending";
};

export const ENGINE_STATUS_CATALOG: EngineCatalogEntry[] = [
  {
    id: "E-01",
    name: "Samsara position poll",
    module: "telematics",
    domain: "Telematics",
    schedule: "~2 min poll",
    expectedWindowHours: 1,
    shouldProduce: true,
    syncKinds: ["samsara_positions", "samsara_position_poll"],
    output: { relation: "telematics.vehicle_locations", tsColumn: "captured_at", companyColumn: null },
    ownerSeat: "CC-3",
    kind: "engine",
  },
  {
    id: "E-02",
    name: "Live-fleet definition",
    module: "telematics/live-fleet",
    domain: "Telematics",
    schedule: "On read",
    expectedWindowHours: null,
    shouldProduce: false,
    syncKinds: [],
    output: null,
    ownerSeat: "Lead",
    kind: "engine",
  },
  {
    id: "E-03",
    name: "Stop-odometer capture",
    module: "telematics/stop-odometer",
    domain: "Telematics",
    schedule: "Per E-01 poll / 15 min",
    expectedWindowHours: 2,
    shouldProduce: true,
    syncKinds: [],
    output: { relation: "telematics.unit_stop_events", tsColumn: "started_at", companyColumn: "operating_company_id" },
    ownerSeat: "Lead",
    kind: "engine",
  },
  {
    id: "E-04",
    name: "Geofence odometer capture",
    module: "geofence-odometer",
    domain: "Telematics",
    schedule: "Cron",
    expectedWindowHours: 6,
    shouldProduce: true,
    syncKinds: ["geofence_odometer_capture"],
    output: { relation: "telematics.geofence_odometer_captures", tsColumn: "created_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-3",
    kind: "engine",
  },
  {
    id: "E-05",
    name: "Real driven miles per leg",
    module: "real-driven-miles",
    domain: "Telematics",
    schedule: "*/15 America/Chicago",
    expectedWindowHours: 2,
    shouldProduce: true,
    syncKinds: ["real_driven_miles"],
    output: { relation: "telematics.load_odometer_segments", tsColumn: "created_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-3",
    kind: "engine",
  },
  {
    id: "E-06",
    name: "Odometer daily snapshot",
    module: "odometer-snapshot",
    domain: "Telematics",
    schedule: "Daily 03:00 CT",
    expectedWindowHours: 36,
    shouldProduce: true,
    syncKinds: ["odometer_snapshot"],
    output: { relation: "telematics.odometer_readings", tsColumn: "created_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-3",
    kind: "engine",
  },
  {
    id: "E-07",
    name: "Samsara address import + fence linking",
    module: "samsara geofences",
    domain: "Telematics",
    schedule: "Daily delta",
    expectedWindowHours: 48,
    shouldProduce: true,
    syncKinds: ["samsara_addresses"],
    output: { relation: "integrations.samsara_addresses", tsColumn: "created_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-3",
    kind: "engine",
  },
  {
    id: "E-08",
    name: "Geofence detector + state machine",
    module: "geofence-detector",
    domain: "Telematics",
    schedule: "On position poll",
    expectedWindowHours: 2,
    shouldProduce: true,
    syncKinds: ["geofence_detector"],
    output: { relation: "geo.geofence_events", tsColumn: "occurred_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-3",
    kind: "engine",
  },
  {
    id: "E-09",
    name: "Dispatch arrival detection",
    module: "arrival-detection",
    domain: "Dispatch",
    schedule: "Each poll",
    expectedWindowHours: 6,
    shouldProduce: true,
    syncKinds: [],
    // E-09: arrivals are geo.geofence_events (load-stop fences); dispatch.stop_arrivals has no readers.
    output: { relation: "geo.geofence_events", tsColumn: "created_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-3",
    kind: "engine",
  },
  {
    id: "E-10",
    name: "Samsara fault-code poller",
    module: "fault-poll",
    domain: "Maintenance",
    schedule: "Cron",
    expectedWindowHours: 6,
    shouldProduce: true,
    syncKinds: ["samsara_fault_poll", "fault_code_poll"],
    output: { relation: "maintenance.samsara_fault_code_history", tsColumn: "occurred_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-3",
    kind: "engine",
  },
  {
    id: "E-11",
    name: "Fault-code alert chain",
    module: "fault-code-alerts",
    domain: "Maintenance",
    schedule: "On new fault row",
    expectedWindowHours: 6,
    shouldProduce: true,
    syncKinds: [],
    output: { relation: "maintenance.samsara_fault_code_history", tsColumn: "occurred_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-3",
    kind: "engine",
  },
  {
    id: "E-12",
    name: "Harsh-events + dashcam poll",
    module: "harsh-events-poll",
    domain: "Safety",
    schedule: "Cron",
    expectedWindowHours: 6,
    shouldProduce: true,
    syncKinds: ["harsh_events_poll"],
    output: { relation: "safety.harsh_events", tsColumn: "event_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-3",
    kind: "engine",
  },
  {
    id: "T-51",
    name: "Samsara DVIR import",
    module: "samsara-dvir-poll",
    domain: "Safety",
    schedule: "*/15 * * * * America/Chicago (1-day window) + 03:40 daily (7-day re-read)",
    expectedWindowHours: 24,
    shouldProduce: true,
    syncKinds: [],
    output: { relation: "safety.dvir_submissions", tsColumn: "created_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-3",
    kind: "engine",
  },
  {
    id: "E-13",
    name: "Samsara webhook projection",
    module: "webhook-projection",
    domain: "Telematics",
    schedule: "Push from Samsara",
    expectedWindowHours: 48,
    shouldProduce: false,
    syncKinds: ["samsara_webhook"],
    output: { relation: "integrations.samsara_webhook_events", tsColumn: "received_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-3",
    kind: "engine",
  },
  {
    id: "E-14",
    name: "PM auto work-order engine",
    module: "pm-auto-engine",
    domain: "Maintenance",
    schedule: "Daily 03:30 America/Chicago + on manual odometer entry",
    expectedWindowHours: 36,
    shouldProduce: true,
    syncKinds: [],
    // One pm_schedule_runs row per run, always -- pm_auto_wo_log only gets rows for actions/skips.
    output: { relation: "maintenance.pm_schedule_runs", tsColumn: "started_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-1",
    kind: "engine",
  },
  {
    id: "E-15",
    name: "PM due engine",
    module: "pm-due-engine",
    domain: "Maintenance",
    schedule: "On read / daily",
    expectedWindowHours: null,
    shouldProduce: false,
    syncKinds: [],
    output: null,
    ownerSeat: "CC-1",
    kind: "engine",
  },
  {
    id: "E-16",
    name: "Work-order linkage",
    module: "work-orders linkage",
    domain: "Maintenance",
    schedule: "On write + CI",
    expectedWindowHours: null,
    shouldProduce: false,
    syncKinds: [],
    output: null,
    ownerSeat: "CC-1",
    kind: "engine",
  },
  {
    id: "E-17",
    name: "Fleet roster integrity",
    module: "fleet roster",
    domain: "Fleet",
    schedule: "Nightly 02:40 CT + on demand",
    // Findings are upserted (last_detected_at) on every run, so the probe reads last_detected_at: a clean fleet
    // still shows the engine alive through the rows it keeps refreshing; a fleet with zero findings ever reads
    // honest-empty rather than broken.
    expectedWindowHours: 36,
    shouldProduce: false,
    syncKinds: [],
    output: { relation: "fleet.roster_findings", tsColumn: "last_detected_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-1",
    kind: "engine",
  },
  {
    id: "E-19",
    name: "Fuel transaction import",
    module: "fuel-transaction-import",
    domain: "Fuel",
    schedule: "Cron / upload",
    expectedWindowHours: 36,
    shouldProduce: true,
    syncKinds: ["loves_card_import", "fuel_import"],
    output: { relation: "fuel.fuel_transactions", tsColumn: "created_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-2",
    kind: "engine",
  },
  {
    id: "E-20",
    name: "Relay fuel ingest",
    module: "relay-fuel-ingest",
    domain: "Fuel",
    schedule: "07:00 America/Chicago",
    expectedWindowHours: 36,
    shouldProduce: true,
    syncKinds: ["relay_fuel_ingest"],
    output: { relation: "integrations.relay_fuel_transactions", tsColumn: "created_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-2",
    kind: "engine",
  },
  {
    id: "E-21",
    name: "Fuel fraud detector",
    module: "fuel-fraud-detector",
    domain: "Integrity",
    schedule: "*/15 America/Chicago",
    expectedWindowHours: 2,
    shouldProduce: true,
    syncKinds: [],
    output: { relation: "fuel.fraud_alerts", tsColumn: "detected_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-2",
    kind: "engine",
  },
  {
    id: "E-22",
    name: "Fuel ↔ GPS match",
    module: "fuel-gps-match",
    domain: "Fuel",
    schedule: "Hourly",
    expectedWindowHours: 6,
    shouldProduce: true,
    syncKinds: ["fuel_gps_match"],
    output: { relation: "fuel.fuel_transactions", tsColumn: "updated_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-2",
    kind: "engine",
  },
  {
    id: "E-23",
    name: "Samsara fuel push + reports",
    module: "fuel-purchase-push",
    domain: "Fuel",
    schedule: "Twice daily",
    expectedWindowHours: 36,
    shouldProduce: false,
    syncKinds: ["fuel_purchase_push"],
    output: null,
    ownerSeat: "CC-3",
    kind: "pending",
  },
  {
    id: "E-24",
    name: "Layover detection",
    module: "layover-detector",
    domain: "Dispatch",
    schedule: "Worker",
    expectedWindowHours: 24,
    shouldProduce: true,
    syncKinds: [],
    output: { relation: "dispatch.driver_layovers", tsColumn: "created_at", companyColumn: "operating_company_id" },
    ownerSeat: "Lead",
    kind: "engine",
  },
  {
    id: "E-25",
    name: "Late-arrival detection",
    module: "late-arrival",
    domain: "Dispatch",
    schedule: "Worker",
    expectedWindowHours: 24,
    shouldProduce: true,
    syncKinds: [],
    output: { relation: "dispatch.late_arrival_aggregates", tsColumn: "computed_at", companyColumn: "operating_company_id" },
    ownerSeat: "Lead",
    kind: "engine",
  },
  {
    id: "E-26",
    name: "Integrity anomaly detector",
    module: "anomaly-detector",
    domain: "Safety",
    schedule: "Cron",
    expectedWindowHours: 24,
    shouldProduce: true,
    syncKinds: [],
    output: { relation: "safety.integrity_findings", tsColumn: "created_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-2",
    kind: "engine",
  },
  {
    id: "E-27",
    name: "Driver scorecards + attribution",
    module: "driver-scorecards",
    domain: "Driver profile",
    schedule: "On read",
    expectedWindowHours: null,
    shouldProduce: false,
    syncKinds: [],
    output: null,
    ownerSeat: "CC-2",
    kind: "engine",
  },
  {
    id: "E-28",
    name: "Complaints against a driver",
    module: "complaints",
    domain: "Driver profile",
    schedule: "On entry",
    expectedWindowHours: null,
    shouldProduce: false,
    syncKinds: [],
    output: null,
    ownerSeat: "CC-2",
    kind: "pending",
  },
  {
    id: "E-29",
    name: "DOT-dwell / border / auto-status",
    module: "dot-dwell + border + auto-status",
    domain: "Dispatch",
    schedule: "On position",
    expectedWindowHours: 24,
    shouldProduce: true,
    syncKinds: [],
    output: { relation: "integrations.auto_status_switch_events", tsColumn: "created_at", companyColumn: "operating_company_id" },
    ownerSeat: "CC-3",
    kind: "engine",
  },
  {
    id: "E-30",
    name: "Driver messaging (Samsara)",
    module: "fleet/messages",
    domain: "Driver",
    schedule: "On send / poll",
    expectedWindowHours: null,
    shouldProduce: false,
    syncKinds: [],
    output: null,
    ownerSeat: "CC-3",
    kind: "pending",
  },
  {
    id: "E-31",
    name: "Samsara Routes push",
    module: "fleet/routes",
    domain: "Dispatch",
    schedule: "On dispatch",
    expectedWindowHours: null,
    shouldProduce: false,
    syncKinds: [],
    output: null,
    ownerSeat: "CC-3",
    kind: "pending",
  },
  {
    id: "E-32",
    name: "Documents / Forms (BOL, POD)",
    module: "fleet/documents",
    domain: "Dispatch",
    schedule: "On stop",
    expectedWindowHours: null,
    shouldProduce: false,
    syncKinds: [],
    output: null,
    ownerSeat: "CC-3",
    kind: "pending",
  },
  {
    id: "E-40",
    name: "Maintenance: Faults view",
    module: "FaultCodeAlertsPage",
    domain: "Maintenance (screen)",
    schedule: "—",
    expectedWindowHours: null,
    shouldProduce: false,
    syncKinds: [],
    output: null,
    ownerSeat: "Cursor",
    kind: "screen",
  },
  {
    id: "E-41",
    name: "Engine status board",
    module: "EngineStatusBoardPage",
    domain: "System (screen)",
    schedule: "—",
    expectedWindowHours: null,
    shouldProduce: false,
    syncKinds: [],
    output: null,
    ownerSeat: "Cursor",
    kind: "screen",
  },
  {
    id: "E-42",
    name: "Dashcam viewer",
    module: "DashcamViewerPage",
    domain: "Safety (screen)",
    schedule: "—",
    expectedWindowHours: null,
    shouldProduce: false,
    syncKinds: [],
    output: null,
    ownerSeat: "Cursor",
    kind: "screen",
  },
  {
    id: "E-43",
    name: "Driver messaging screen",
    module: "DriverMessagingPage",
    domain: "Driver Hub (screen)",
    schedule: "—",
    expectedWindowHours: null,
    shouldProduce: false,
    syncKinds: [],
    output: null,
    ownerSeat: "Cursor",
    kind: "screen",
  },
  {
    id: "E-44",
    name: "Stops + miles on unit/driver profile",
    module: "StopsMiles views",
    domain: "Fleet / Driver (screen)",
    schedule: "—",
    expectedWindowHours: null,
    shouldProduce: false,
    syncKinds: [],
    output: null,
    ownerSeat: "Cursor",
    kind: "screen",
  },
];

export const ENGINE_STATUS_CATALOG_COUNT = ENGINE_STATUS_CATALOG.length;
