// Architecture verification helper: keeps an explicit tab list in pages/safety.
export const TABS = [
  { id: "driver-files" },
  { id: "drug-alcohol" },
  { id: "safety-meetings" },
  { id: "hos" },
  { id: "hos-violations" },
  { id: "idvr" },
  { id: "dot-inspections" },
  { id: "driver-scoring" },
  { id: "csa-score" },
  { id: "dot-compliance" },
  { id: "safety-events" },
  { id: "accidents" },
  { id: "damage-reports" },
  { id: "trailer-interchanges" },
  { id: "cargo-claims" },
  { id: "internal-fines" },
  { id: "external-fines" },
  { id: "complaints" },
  { id: "escrow-record" },
  { id: "geofence-alerts" },
  { id: "insurance" },
  { id: "permits" },
  { id: "integrity-reports" },
  { id: "driver-scheduler" },
  { id: "leave-requests" },
  { id: "leave-balances" },
  { id: "settings" },
];
