import type { FastifyInstance } from "fastify";
import { registerInvoiceRoutes } from "./invoices.routes.js";
import { registerAccountingInvoiceHtmlRoutes } from "./invoice-render.routes.js";
import { registerInvoiceLineRoutes } from "./invoice-lines.routes.js";
import { registerPaymentsRoutes } from "./payments.routes.js";
import { registerPaymentApplicationsRoutes } from "./payment-applications.routes.js";
import { registerCustomerPaymentsRoutes } from "./customer-payments.routes.js";
import { registerVendorBillPaymentsRoutes } from "./vendor-bill-payments.routes.js";
import { registerFactoringAdvancesRoutes } from "./factoring-advances.routes.js";
import { registerBillsRoutes } from "./bills.routes.js";
import { registerJournalEntryRoutes } from "./journal-entries.routes.js";
import { registerExpenseLoadLookupRoutes } from "./load-lookup.routes.js";
import { registerExpenseRoutes } from "./expenses.routes.js";
import { registerAccountingP7Wave2Routes } from "./p7-wave2.routes.js";
import { registerPostingEngineRoutes } from "./posting-engine.routes.js";
import { registerTrialBalanceRoutes } from "./trial-balance.routes.js";
import { registerAccountingPeriodsReadRoutes } from "./periods.routes.js";
import { registerProfitLossRoutes } from "./profit-loss.routes.js";
import { registerBalanceSheetRoutes } from "./balance-sheet.routes.js";
import { registerCashFlowRoutes } from "./cash-flow.routes.js";
import { registerArAgingRoutes } from "./ar-aging.routes.js";
import { registerApAgingRoutes } from "./ap-aging.routes.js";
import { registerDateRangesRoutes } from "./date-ranges.routes.js";
import { registerStatementExportRoutes } from "./statement-export.routes.js";
import { registerExpenseCategoryMapRoutes } from "./expense-category-map/routes.js";
import { registerCoaRolesRoutes } from "./coa-roles/routes.js";
import { registerFactorReconciliationRoutes } from "./factor-reconciliation/routes.js";
import { registerSalesTaxRoutes } from "./sales-tax/routes.js";

export async function registerAccountingRoutes(app: FastifyInstance) {
  await registerInvoiceRoutes(app);
  await registerAccountingInvoiceHtmlRoutes(app);
  await registerInvoiceLineRoutes(app);
  await registerPaymentsRoutes(app);
  await registerPaymentApplicationsRoutes(app);
  await registerCustomerPaymentsRoutes(app);
  await registerVendorBillPaymentsRoutes(app);
  await registerFactoringAdvancesRoutes(app);
  await registerBillsRoutes(app);
  await registerJournalEntryRoutes(app);
  await registerExpenseLoadLookupRoutes(app);
  await registerExpenseRoutes(app);
  await registerAccountingP7Wave2Routes(app);
  await registerPostingEngineRoutes(app);
  await registerTrialBalanceRoutes(app);
  await registerAccountingPeriodsReadRoutes(app);
  await registerProfitLossRoutes(app);
  await registerBalanceSheetRoutes(app);
  await registerCashFlowRoutes(app);
  await registerArAgingRoutes(app);
  await registerApAgingRoutes(app);
  await registerDateRangesRoutes(app);
  await registerStatementExportRoutes(app);
  await registerExpenseCategoryMapRoutes(app);
  await registerCoaRolesRoutes(app);
  await registerFactorReconciliationRoutes(app);
  await registerSalesTaxRoutes(app);
}
