export const colors = {
  topbarBg: "#0F1219",
  sidebarBg: "#1B2333",
  sidebarBorder: "#2A3242",
  sidebarTextMuted: "#9CA3AF",
  sidebarTextActive: "#FFFFFF",
  sidebarActiveBorder: "#3B82F6",
  bodyBg: "#F7F8FA",
  cardBg: "#FFFFFF",
  cardBorder: "#E5E7EB",
  cardBorderStrong: "#D1D5DB",
  pageHeading: "#0F1219",
  bodyText: "#1F2937",
  mutedText: "#6B7280",
  tinyLabel: "#9CA3AF",
  safety: { strong: "#DC2626", soft: "#FEE2E2" },
  maintenance: { strong: "#6B7280", soft: "#F3F4F6" },
  dispatch: { strong: "#2563EB", soft: "#DBEAFE" },
  fuel: { strong: "#CA8A04", soft: "#FEF3C7" },
  drivers: { strong: "#16A34A", soft: "#DCFCE7" },
  fleet: { strong: "#7C3AED", soft: "#EDE9FE" },
  accounting: { strong: "#374151", soft: "#F3F4F6" },
  crit: { strong: "#DC2626", soft: "#FEE2E2" },
  warn: { strong: "#CA8A04", soft: "#FEF3C7" },
  info: { strong: "#2563EB", soft: "#DBEAFE" },
  positive: { strong: "#16A34A", soft: "#DCFCE7" },
  pwaBg: "#0F1219",
  pwaCardBg: "#1A2030",
  pwaCardBorder: "#2A3242",
  pwaText: "#E5E7EB",
  pwaTextMuted: "#9CA3AF",
} as const;

export const typography = {
  fontSerif: "'Source Serif Pro', 'Charter', Georgia, serif",
  fontSans: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  pageHeading: 22,
  pageSubtitle: 12,
  sectionSubhead: 11,
  tabItem: 12,
  bodyText: 13,
  bodyTextSmall: 12,
  tableRow: 11,
  kpiLabel: 9,
  kpiNumber: 14,
  statusBadge: 10,
  panelHeader: 11,
  tightUpper: "0.6px",
  looseUpper: "0.8px",
} as const;

export const spacing = {
  topbarHeight: 48,
  topbarPaddingY: 12,
  topbarPaddingX: 18,
  sidebarWidth: 80,
  sidebarItemHeight: 56,
  sidebarItemPaddingY: 8,
  pageContentPadding: 24,
  kpiCardHeight: 30,
  kpiCardPaddingX: 12,
  kpiCardGap: 6,
  subAreaTileHeight: 60,
  subAreaTilePadding: 10,
  subAreaTileGap: 8,
  subAreaTileBorderLeft: 3,
  panelHeaderHeight: 20,
  panelDataRowHeight: 22,
  panelPaddingX: 12,
  panelPaddingY: 10,
  panelBorderTop: 2,
  tableRowHeight: 24,
  tableHeaderHeight: 26,
  tableCellPaddingX: 8,
  buttonHeightPrimary: 32,
  buttonHeightSecondary: 28,
  buttonHeightSmall: 24,
  buttonPaddingX: 12,
  radiusCard: 4,
  radiusPill: 2,
  radiusButton: 4,
  sectionGap: 16,
  panelGap: 12,
} as const;

export const z = {
  dropdown: 30,
  modal: 50,
  toast: 60,
} as const;
